export interface FaqItem {
  question: string;
  answer: string;
}

/**
 * Single source of truth for the page's FAQ. Rendered visibly by the `Faq`
 * component and mirrored into the JSON-LD `FAQPage` structured data in
 * `page.tsx`, so keep the two in sync automatically by importing from here.
 */
export const faqItems: FaqItem[] = [
  {
    question: "What happens to a multi-sheet Excel workbook?",
    answer:
      "Every worksheet becomes its own CSV file, named after the workbook and the sheet (for example sales-Q1.csv). Rename any of them before downloading, grab them one at a time, or download the whole set as a single zip.",
  },
  {
    question: "What happens to my formula cells?",
    answer:
      "The CSV contains the computed value, not the formula text. Excel stores the last computed result inside the file and that is what we read. A workbook generated by a script that never cached its results will show those cells as empty.",
  },
  {
    question: "How are dates and numbers formatted?",
    answer:
      "Dates come out as YYYY-MM-DD. Numbers come out plain — no currency symbols, no thousands separators — so the CSV stays easy to parse.",
  },
  {
    question: "Are my files uploaded to a server?",
    answer:
      "No. The conversion happens entirely in your browser — your Excel files never leave your device.",
  },
  {
    question: "Why was my .xls file rejected?",
    answer:
      "The old binary .xls format is not supported. Open the file in Excel (or any spreadsheet app) and use Save As to store it as .xlsx, then convert it here.",
  },
  {
    question: "How big can the files be?",
    answer:
      "Up to 10 files at a time, 20MB per file, and 50MB in total. Everything runs on your own machine, so those limits keep the browser tab responsive.",
  },
  {
    question: "Is this Excel to CSV converter free?",
    answer:
      "Yes. Converting Excel (.xlsx) workbooks to CSV is completely free, with no signup required.",
  },
];
